language: java
sudo: false # faster builds
install: true

jdk:
 - oraclejdk8

script:
 - chmod +x gradlew
 - ./gradlew clean
 - ./gradlew build

cache:
  directories:
    - '$HOME/.gradle'
    - '.gradle'