language: java
sudo: false # faster builds
install: true

install: gradle wrapper --gradle-version 4.2 # чтобы не заталкивать враппе в репу

jdk:
 - oraclejdk8

script:
 - chmod +x gradlew
 - ./gradlew test
 - ./gradlew build
 - ./gradlew jar

cache:
  directories:
    - '$HOME/.gradle'
    - '.gradle'

# before_deploy:
  # Set up git user name and tag this commit
  # - git config --local user.name "rarescrap"
  # - git config --local user.email "rarescrap@gmail.com"
  # - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: 518c97382dee98db13b059a4bcc20a88c8ecf551
  file: travis.test-1.0-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: true