language: java
sudo: false # faster builds
install: true

install: gradle wrapper --gradle-version 4.2 # чтобы не заталкивать враппе в репу

jdk:
 - oraclejdk8

script:
 - chmod +x gradlew
 - ./gradlew test
 - ./gradlew build
 - ./gradlew jar

deploy:
  provider: releases
  api_key: 518c97382dee98db13b059a4bcc20a88c8ecf551
  file: build/lib/travis.test-1.0-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

cache:
  directories:
    - '$HOME/.gradle'
    - '.gradle'